# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Form(object):
    def setupUi(self, Ui_Form):
        Ui_Form.setObjectName("Ui_Form")
        Ui_Form.resize(792, 354)
        self.centralwidget = QtWidgets.QWidget(Ui_Form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 731, 264))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        self.nameTextEdit.setFont(font)
        self.nameTextEdit.setObjectName("nameTextEdit")
        self.verticalLayout.addWidget(self.nameTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hostTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.hostTextEdit.setObjectName("hostTextEdit")
        self.horizontalLayout.addWidget(self.hostTextEdit)
        self.portTextEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.portTextEdit.setObjectName("portTextEdit")
        self.horizontalLayout.addWidget(self.portTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        Ui_Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menubar.setObjectName("menubar")
        self.menuLogin_Page = QtWidgets.QMenu(self.menubar)
        self.menuLogin_Page.setObjectName("menuLogin_Page")
        Ui_Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_Form)
        self.statusbar.setObjectName("statusbar")
        Ui_Form.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuLogin_Page.menuAction())

        self.retranslateUi(Ui_Form)
        QtCore.QMetaObject.connectSlotsByName(Ui_Form)

    def retranslateUi(self, Ui_Form):
        _translate = QtCore.QCoreApplication.translate
        Ui_Form.setWindowTitle(_translate("Ui_Form", "ChatApplication"))
        self.nameTextEdit.setHtml(_translate("Ui_Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Palatino Linotype\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:600; font-style:italic;\">Enter Your Username</span></p></body></html>"))
        self.hostTextEdit.setHtml(_translate("Ui_Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Enter The Recipients IPV4 Address</span></p></body></html>"))
        self.portTextEdit.setHtml(_translate("Ui_Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Enter The Recipients Port Number</span></p></body></html>"))
        self.pushButton.setText(_translate("Ui_Form", "START CHAT!!"))
        self.menuLogin_Page.setTitle(_translate("Ui_Form", "Start Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_Form = QtWidgets.QMainWindow()
    ui = Ui_Ui_Form()
    ui.setupUi(Ui_Form)
    Ui_Form.show()
    sys.exit(app.exec_())
