# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inappdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ChatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 751, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 745, 427))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SentMessages = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.SentMessages.setGeometry(QtCore.QRect(0, 8, 381, 411))
        self.SentMessages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SentMessages.setObjectName("SentMessages")
        self.RecievedMessages = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.RecievedMessages.setGeometry(QtCore.QRect(380, 10, 361, 411))
        self.RecievedMessages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RecievedMessages.setObjectName("RecievedMessages")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setItalic(True)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("SendButton")
        self.verticalLayout.addWidget(self.pushButton)
        ChatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuStart_Page = QtWidgets.QMenu(self.menubar)
        self.menuStart_Page.setObjectName("menuStart_Page")
        self.menuCurrent_Message = QtWidgets.QMenu(self.menubar)
        self.menuCurrent_Message.setObjectName("menuCurrent_Message")
        ChatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChatWindow)
        self.statusbar.setObjectName("statusbar")
        ChatWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuStart_Page.menuAction())
        self.menubar.addAction(self.menuCurrent_Message.menuAction())

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "InChat"))
        self.textEdit.setText(_translate("ChatWindow", "ENTER YOUR MESSAGE"))
        self.pushButton.setText(_translate("ChatWindow", "Send Message"))
        self.menuStart_Page.setTitle(_translate("ChatWindow", "Start Page"))
        self.menuCurrent_Message.setTitle(_translate("ChatWindow", "Current Message"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChatWindow = QtWidgets.QMainWindow()
    ui = Ui_ChatWindow()
    ui.setupUi(ChatWindow)
    ChatWindow.show()
    sys.exit(app.exec_())
