# -*- coding: utf-8 -*-

# userInput implementation generated from reading ui file 'mainChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, userChat):
        userChat.setObjectName("userInput")
        userChat.resize(648, 504)
        self.userMsgInput = QtWidgets.QPushButton(userChat)
        self.userMsgInput.setGeometry(QtCore.QRect(530, 390, 101, 71))
        self.userMsgInput.setObjectName("userNameInput")
        self.userTxt = QtWidgets.QTextEdit(userChat)
        self.userTxt.setGeometry(QtCore.QRect(10, 390, 501, 71))
        self.userTxt.setObjectName("userTxt")
        self.textWindow = QtWidgets.QTextBrowser(userChat)
        self.textWindow.setGeometry(QtCore.QRect(9, 10, 631, 361))
        self.textWindow.setObjectName("textWindow")

        self.retranslateUi(userChat)
        QtCore.QMetaObject.connectSlotsByName(userChat)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("userInput", "userInput"))
        self.userMsgInput.setText(_translate("userInput", "Send Msg"))
